server/src/main/java/com/codecozy/server/context/StatusCode.java, server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/dto/request/BookCreateRequest.java, server/src/main/java/com/codecozy/server/dto/response/DefaultResponse.java, server/src/main/java/com/codecozy/server/entity/Book.java, server/src/main/java/com/codecozy/server/service/BookService.java
copyProperties에서 builder 사용으로 변경
=> refactor: builder 사용 형식으로 변경

server/src/main/java/com/codecozy/server/service/BookService.java
=> fix: 참고사항이 뜨지 않도록 수정

server/build.gradle, server/src/main/java/com/codecozy/server/controller/MemberController.java, server/src/main/java/com/codecozy/server/dto/CustomUserDetails.java, server/src/main/java/com/codecozy/server/dto/request/SignUpKakaoRequest.java, server/src/main/java/com/codecozy/server/dto/response/SignUpKakaoResponse.java, server/src/main/java/com/codecozy/server/entity/Member.java, server/src/main/java/com/codecozy/server/repository/MemberRepository.java, server/src/main/java/com/codecozy/server/security/JwtAuthenticateFilter.java, server/src/main/java/com/codecozy/server/security/SecurityConfig.java, server/src/main/java/com/codecozy/server/security/TokenProvider.java, server/src/main/java/com/codecozy/server/service/BookService.java, server/src/main/java/com/codecozy/server/service/CustomUserDetailsService.java, server/src/main/java/com/codecozy/server/service/MemberService.java, server/src/main/resources/jwt.yml
- Spring Security 적용 및 Security Filter 구현
- JWT 발급 구현
- 카카오 회원가입 API 구현
- 닉네임 중복 검사 API 구현
- 그 외 코드 스타일 조정함
=> 유저 생성 관련 로직 구현

server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/dto/request/BookmarkRequest.java, server/src/main/java/com/codecozy/server/dto/request/MemoRequest.java, server/src/main/java/com/codecozy/server/dto/request/PersonalDictionaryRequest.java, server/src/main/java/com/codecozy/server/dto/request/ReadingBookCreateRequest.java, server/src/main/java/com/codecozy/server/dto/request/ReviewCreateRequest.java, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/entity/BookReview.java, server/src/main/java/com/codecozy/server/entity/BookReviewReaction.java, server/src/main/java/com/codecozy/server/entity/Bookmark.java, server/src/main/java/com/codecozy/server/entity/KeywordReview.java, server/src/main/java/com/codecozy/server/entity/Memo.java, server/src/main/java/com/codecozy/server/entity/PersonalDictionary.java, server/src/main/java/com/codecozy/server/repository/BookmarkRepository.java, server/src/main/java/com/codecozy/server/repository/KeywordReviewRepository.java, server/src/main/java/com/codecozy/server/repository/MemoRepository.java, server/src/main/java/com/codecozy/server/repository/PersonalDictionaryRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
=> feat: 리뷰 작성, 책별 대표 위치 등록, 인물사전 등록, 메모 등록, 책갈피 등록 API 구현

server/src/main/java/com/codecozy/server/entity/BookReviewReaction.java, server/src/main/java/com/codecozy/server/repository/MemberLocationRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
위치값이 null이 넘어오는 경우 뜨는 오류 fix 및 위치값과 관련된 POST API 일부 로직 변경
=> fix: 위치값이 null이 넘어오는 경우 뜨는 오류 fix

server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/dto/request/GetAllLocationRequest.java, server/src/main/java/com/codecozy/server/dto/response/GetAllLocationResponse.java, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/entity/LocationList.java, server/src/main/java/com/codecozy/server/repository/BookRecordRepository.java, server/src/main/java/com/codecozy/server/repository/BookmarkRepository.java, server/src/main/java/com/codecozy/server/repository/LocationRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
전체 위치 조회 API 구현
마지막으로 조회된 위치가 다른 위치를 덮어씌우는 문제 해결
=> feat: 전체 위치 조회 API 구현

server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/dto/request/BookmarkRequest.java, server/src/main/java/com/codecozy/server/dto/request/LocationRequest.java, server/src/main/java/com/codecozy/server/dto/request/ReadingBookCreateRequest.java, server/src/main/java/com/codecozy/server/dto/request/deleteRecentLocationRequest.java, server/src/main/java/com/codecozy/server/dto/response/GetRecentLocationResponse.java, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/repository/BookRecordRepository.java, server/src/main/java/com/codecozy/server/repository/BookmarkRepository.java, server/src/main/java/com/codecozy/server/repository/MemberLocationRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
최근 등록 위치 조회 API 구현
최근 등록 위치 삭제 API 구현
책별 대표 위치 수정 API 구현
책별 대표 위치 삭제 API 구현
=> feat: 위치 관련 API 구현

server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/repository/BookReviewReactionRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
한줄평 삭제 API 구현
리뷰 전체 삭제 API 구현
마지막 읽은 날짜 변경 API 구현
읽기 시작한 날짜 변경 API 구현
=> feat: PATCH API, DELETE API 일부 구현

server/src/main/java/com/codecozy/server/dto/request/DeletePersonalDictionaryRequest.java, server/src/main/java/com/codecozy/server/dto/request/DeleteUuidRequest.java, server/src/main/java/com/codecozy/server/dto/request/ReactionCommentRequest.java, server/src/main/java/com/codecozy/server/dto/request/ReadingBookCreateRequest.java, server/src/main/java/com/codecozy/server/dto/request/ReportCommentRequest.java, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/repository/BookReviewReactionRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
퍼센트 계산 오류 수정 및 API 명세서와 변수명 통일
=> fix: 오류 수정 및 변수명 변경

server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/dto/request/CommentReactionRequest.java, server/src/main/java/com/codecozy/server/dto/request/DeleteReactionRequest.java, server/src/main/java/com/codecozy/server/dto/request/ReactionCommentRequest.java, server/src/main/java/com/codecozy/server/entity/BookReviewReaction.java, server/src/main/java/com/codecozy/server/entity/BookReviewReviewer.java, server/src/main/java/com/codecozy/server/repository/BookReviewReviewerRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
한줄평 반응 추가/수정/삭제 API 구현 완료 및 DB 수정사항 반영
=> feat: 한줄평 반응 관련 API 구현

server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/entity/BookReview.java, server/src/main/java/com/codecozy/server/entity/KeywordReview.java, server/src/main/java/com/codecozy/server/service/BookService.java
읽고 싶은 책 등록 API 구현
리뷰 전체 수정 API 구현
=> feat: 읽고 싶은 책 등록, 리뷰 전체 수정 API 구현

server/src/main/java/com/codecozy/server/controller/HomeController.java, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/service/HomeService.java
- 홈(메인) 화면에서만 사용하는 기능은 HomeController와 HomeService로 따로 분리함
=> feat: 읽고 있는 책 숨기기 & 꺼내기 API 구현

server/src/main/java/com/codecozy/server/dto/request/ReviewCreateRequest.java, server/src/main/java/com/codecozy/server/service/BookService.java
신고하기 API 수정: 해당 댓글을 신고했던 경우 '이미 신고한 리뷰' 충돌 발생
리뷰 작성 API 수정: 명세서에 추가된 date 필드 추가
=> refactor: API 수정

server/src/main/java/com/codecozy/server/dto/response/GetReadingResponse.java, server/src/main/java/com/codecozy/server/service/HomeService.java
- 서비스 요구사항에 따라 readingPercent 값을 int형으로 보내도록 변경
=> fix: (home) 읽고 있는 책 조회 API 변경사항 반영

server/build.gradle, server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/dto/response/GetSearchBookResponse.java, server/src/main/java/com/codecozy/server/service/BookService.java
feat: 알라딘 OpenAPI request
feat: 알라딘 OpenAPI response parsing
=> feat: 도서 정보 초기 조회 API 구현중

server/src/main/java/com/codecozy/server/composite_key/MemberLocationKey.java, server/src/main/java/com/codecozy/server/entity/Badge.java, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/entity/BookReview.java, server/src/main/java/com/codecozy/server/entity/Bookmark.java, server/src/main/java/com/codecozy/server/entity/MemberLocation.java, server/src/main/java/com/codecozy/server/entity/Memo.java, server/src/main/java/com/codecozy/server/service/BookService.java, server/src/main/java/com/codecozy/server/service/ConverterService.java, server/src/main/java/com/codecozy/server/service/MemberService.java
- Converter 클래스 내 LocalDate(yyyy-MM-dd) <-> String date(yyyy.MM.dd) 상호 변환 메소드 작성
- 이후 기존 코드들이 Converter 클래스의 메소드를 이용하도록 코드 리펙토링
- date 관련 필드들의 타입을 String에서 서비스 로직에 따라 LocalDate 또는 LocalDateTime으로 변경
=> 5/8 date 필드 관련 DB 변경사항 반영 및 코드 리펙토링

server/src/main/java/com/codecozy/server/dto/request/BookCreateRequest.java, server/src/main/java/com/codecozy/server/dto/response/GetSearchResponse.java, server/src/main/java/com/codecozy/server/entity/Book.java, server/src/main/java/com/codecozy/server/repository/BookRecordRepository.java, server/src/main/java/com/codecozy/server/repository/BookRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java, server/src/main/java/com/codecozy/server/service/HomeService.java
- 알라딘 내 검색 정보를 활용한 검색 API 구현 완료
- Book Entity에 publisher, publicationDate 필드 추가
- 책 등록 API, 읽고 싶은 책 등록 API 수정
- Book Entity 구조 변화에 따른 수정
- 자세한 내용은 해당 커밋 참고 (5064950aa47d18033b7ec1d4c8e5be32752d1f80)
=> 검색 API 구현 완료 및 일부 API 리펙토링

server/src/main/java/com/codecozy/server/entity/BookReview.java, server/src/main/java/com/codecozy/server/repository/BookReviewRepository.java, server/src/main/java/com/codecozy/server/repository/KeywordReviewRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
feat: 도서정보 초기조회 모든 Output List 구현
=> feat: 도서정보 초기조회 API 구현

server/src/main/java/com/codecozy/server/dto/response/AllLocationResponse.java, server/src/main/java/com/codecozy/server/dto/response/AllMarkerResponse.java, server/src/main/java/com/codecozy/server/service/BookService.java
rename: 새로 추가한 DTO 중 get이 붙은 DTO 이름 변경
=> rename: dto 이름 변경

server/src/main/java/com/codecozy/server/repository/BookRecordRepository.java, server/src/main/java/com/codecozy/server/repository/BookReviewRepository.java, server/src/main/java/com/codecozy/server/repository/BookReviewReviewerRepository.java, server/src/main/java/com/codecozy/server/repository/BookmarkRepository.java, server/src/main/java/com/codecozy/server/repository/KeywordReviewRepository.java, server/src/main/java/com/codecozy/server/repository/MemberLocationRepository.java, server/src/main/java/com/codecozy/server/repository/MemoRepository.java, server/src/main/java/com/codecozy/server/repository/PersonalDictionaryRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
- c0d2abf9d13e2abf573e32e95dafc50336214bac 커밋에 수정 필요 부분을 일부 표시해두었으니 확인 후 수정 부탁드립니다!
=> fix: 일부 Jpa Repository 클래스 형식 수정 및 수정 필요 부분 표시

server/src/main/java/com/codecozy/server/repository/BookReviewReviewerRepository.java, server/src/main/java/com/codecozy/server/service/BookService.java
- #41 의 변경사항에 따라 한줄평 삭제 로직 변경
- (커밋 제목에 PR 링크 연결 시도하다가 의미없는 커밋이 생성되었습니다...... 양해부탁드립니다)
=> fix: BookService - 한줄평 삭제 코드 일부 수정

server/build.gradle
=> docs: 로컬 서버 배포를 위한 plugin 추가

server/src/main/java/com/codecozy/server/service/BookService.java
fix: 신고하기 API에서 NULL값을 참조하는 오류 수정, 읽고싶은 책 등록 API에서 category가 설정되지 않아 트랜잭션에서 발생하는 문제 수정, 한줄평 반응 수정/삭제 API에서 실행 시 DB가 수정되지 않는 오류 수정
=> fix: API 오류 수정

server/src/main/java/com/codecozy/server/service/BookService.java
fix: 한줄평 추가조회 API에서 최신순으로 조회 시 NullPointerException이 발생하던 오류 수정
=> fix: 한줄평 추가조회 API NullPointerException 오류 수정

server/src/main/java/com/codecozy/server/service/BookService.java
fix: 한줄평 추가조회 API에서 한줄평이 없는 경우도 성공으로 출력되는 오류 수정
fix: 응답용 StatusCode와 HttpStatus를 상황에 맞게 수정
feat: 응답용 분기 코드 일부 추가
=> fix: 한줄평 추가조회 API에서 한줄평이 없는 경우도 성공으로 출력되는 오류 수정

server/build.gradle, server/src/main/java/com/codecozy/server/entity/BookRecord.java, server/src/main/java/com/codecozy/server/service/BookService.java, server/src/main/resources/application.yml
- 특정 상황에서 마지막 리뷰 작성일 업데이트 버그 수정
- 책 삭제가 제대로 이뤄지지 않던 문제 수정
=> fix: 일부 버그 수정

server/src/main/java/com/codecozy/server/service/BookService.java
feat: 5개 API(마크 세부 조회, 지도 마크 조회, 최근 등록 위치 조회, 최근 등록 위치 삭제, 책별 대표 위치 변경) 응답 분기 추가
=> feat: 5개 API 응답 분기 추가

server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/service/BookService.java
fix: 책별 대표 위치 변경 API 호출 오류 문제 수정
fix: 신고하기 API 중복 신고 오류 수정
=> fix: 책별 대표 위치 변경, 신고하기 API 오류 수정

server/build.gradle, server/src/main/java/com/codecozy/server/controller/MemberController.java, server/src/main/java/com/codecozy/server/dto/request/SignInAppleRequest.java, server/src/main/java/com/codecozy/server/dto/request/SignUpAppleRequest.java, server/src/main/java/com/codecozy/server/entity/Member.java, server/src/main/java/com/codecozy/server/entity/MemberApple.java, server/src/main/java/com/codecozy/server/repository/MemberAppleRepository.java, server/src/main/java/com/codecozy/server/service/AppleTokenService.java, server/src/main/java/com/codecozy/server/service/MemberService.java
=> feat: 애플 회원가입, 애플 로그인 API 구현

server/src/main/java/com/codecozy/server/dto/request/DeletePersonalDictionaryRequest.java, server/src/main/java/com/codecozy/server/service/BookService.java
fix: 삭제 오류가 발생하는 API와 날짜 저장 오류가 발생하는 API 수정
=> fix: 인물사전 삭제 API, 책갈피 삭제 API, 마지막 읽은 날짜 API, 읽기 시작한 날짜 변경 API 오류 수정

server/src/main/java/com/codecozy/server/service/BookService.java
fix: 리뷰 전체 수정 API에서 비어있는 키워드, 선택 리뷰, 한줄평과 관련된 데이터/레코드가 삭제되지 않는 오류 수정
=> fix: 리뷰 전체 수정 API에서 비어있어야하는 레코드가 삭제되지 않는 오류 수정

server/build.gradle, server/src/main/java/com/codecozy/server/dto/response/MainBooksResponse.java, server/src/main/java/com/codecozy/server/service/BookService.java, server/src/main/java/com/codecozy/server/service/HomeService.java
- 메인화면 조회 시 읽고 있는 책, 다 읽은 책에 대하여 각 책의 리뷰 작성 여부를 응답 필드에 추가함
- 현재까지의 내용 0.0.3v으로 배포
=> feat: 메인화면 조회 시 요구사항 반영

server/src/main/java/com/codecozy/server/controller/BookController.java, server/src/main/java/com/codecozy/server/dto/request/ModifyPageRequest.java, server/src/main/java/com/codecozy/server/service/BookService.java
읽은 페이지 API 삭제
- 해당 API에서 사용한 DTO(`ModifyPageRequest`) 삭제
- 관련 service 로직 및 함수(`modifyReadingPage`) 삭제
- 관련 controller 함수(`modifyReadingPage`) 삭제
X (단순 코드 삭제라 테스트 수행하지 않음)
=> remove: 읽은 페이지 API 삭제

README.md
=> docs: Test Code Convention 추가

server/src/main/java/com/codecozy/server/service/BookService.java, server/src/test/java/com/codecozy/server/cache/MemberCacheManagerTest.java
기존에 설정한 카테고리 용어사전 이름으로 카테고리 형식을 지정하기 위함
main에 저장된 코드를 기반으로 카테고리 형식 설정 코드를 추가
Postman으로 카테고리 이름이 설정한 형식대로 출력되는지 테스트
분기를 다시 생성하면서 main에 있는 코드가 그대로 복사됐는데, 로컬에서는 pull 받지 않은 부분이 있어서 이 부분에서 충돌이 발생했던 것 같습니다!! 코드 변경사항은 기존에 올린 PR과 같아요! 항상 확인해주셔서 감사합니다!! 그리고 저쪽 PR에는 답장을 못 달았는데... 항상 과분한 칭찬 감사합니다!!!!❤️‍🔥
=> main 코드를 베이스로 카테고리 형식 설정 코드 추가

server/src/main/java/com/codecozy/server/context/Category.java, server/src/main/java/com/codecozy/server/dto/response/SearchBookDataResponse.java, server/src/main/java/com/codecozy/server/service/BookService.java
도서정보 초기조회 API에서 다음 두 개의 이슈가 발생하여 이를 해결하기 위함
1. categoryName이 프론트에 String 값으로 전달되어 프론트에서 변환하는 일이 발생
2. 알라딘 OpenAPI를 사용해 책 표지를 불러오면 화질이 깨져보이는 문제 발생
1. categoryName이 String 값이 아닌, int 코드값으로 변환되어 전달되도록 수정
- 카테고리 정보를 담은 enum 생성
2. 표지 이미지를 가장 큰 사이즈로 불러오도록 변경
3. 도서 정보를 호출하는 메서드 getBookDate()의 이름을 의미에 맞게 getBookData()로 변경
1. postman으로 categoryname 값이 변환되어 오는지 테스트
2. postman으로 응답받은 표지 이미지 url이 큰 사이즈의 이미지인지 테스트
-
=> refactor: 도서정보 초기조회 API 이슈 수정
